- task: JFrogGenericArtifacts@1
  inputs:
    command: 'Upload'
    connection: 'BQX'
    specSource: 'taskConfiguration'
    fileSpec: |
      {
        "files": [
          {
            "pattern": "**/target/*"
            "target": "https://perumal09062001.jfrog.io/artifactory/BWR/"
          }
        ]
      }
    failNoOp: true
# Archive your static HTML project and save it with the build record.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(build.sourcesDirectory)'
    includeRootFolder: false
- task: PublishBuildArtifacts@1
